# Generated by Django 3.1.7 on 2021-04-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('accountAmount', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionID', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(default=0)),
                ('Message', models.CharField(max_length=100, null=True)),
                ('Receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiver', to='User.account')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='User.account')),
            ],
        ),
    ]
