# Generated by Django 3.1.7 on 2021-04-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Sender',
            new_name='username',
        ),
    ]
